apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 2
  selector:
    app: helloworld-replica
  template:
    metadata:
      labels:
        app: helloworld-replica
    spec:
      containers:
      - name: docker-demo
        image: kruttik/docker-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
